# Parcial Fake 1

## 1. Integración de Montecarlo

Definamos las ecuaciones de cada una de las funciones mostradas.

a. $f(x,y) = (x-1)^2 + (y-1)^2 = 1$
b. $k(x,y) = x^2+y^2 = 1$

Despejemos con el fin de poder realizar la integración.

a. $(x-1)^2 + (y-1)^2 = 1$
i. $1 - (x-1)^2 = (y-1)^2$
ii. $\sqrt{1 - (x-1)^2} + 1 = y$
b. $x^2+y^2 = 1$
i. $1-x^2 = y^2$
i. $\sqrt{1-x^2} = y$

Pasamos a los diferenciales y aplicamos integrales.

a. $\sqrt{1 - (x-1)^2} + 1 = y$
i. $\int_{0}^{1} \sqrt{1-(x-1)^2} dx = F(x)$
b. $\sqrt{1-x^2} = y$
i. $\int_{0}^{1} \sqrt{1-x^2} dx = K(x)$

```{r}

```

## 2. Craps: Los dados

```{r}
    win = c(7, 11)
    lose = c(2,3,12)

    runs = 10000
    won = 0

    for (i in 1:runs) {
       dice = sum(sample(1:26, 2, replace = TRUE))

       if (dice %in% win) {
            won = won + 1
       } else if (dice %in% lose) {
            next
       } else {
           repeat {
               throw = sum(sample(1:6, 2, replace = TRUE))
               if (dice == throw) {
                   won = won + 1
                   break
               } else if (throw == 7) {
                   break
               }
           }
       }
    }

```

```{r, echo= FALSE}
    sprintf("Won %s out of %s", won, runs)
    sprintf("Winning Chance %s", won/runs)

```

## 3. Método de rechazo

```{r}

U = floor(runif(100)*10)+1
P = dnorm(rnorm(10))


```
