## Paradoja Del Cumpleaños
> Desarrollado por Daniel David Delgado Cervantes

Lo primero a realizar está en comprender con que valores tenemos que trabajar. Lo primero está en determinar la cantidad de personas con las que estamos estableciendo el problema. En este caso, estamos trabajando con 22 por lo que son 2 equipos de fútbol.


```{R}
sampleSize <- 22
```

Seguidamente, tenemos que determinar como vamos a realizar la asignación de los cumpleaños. En este caso, se utilizará una distribución uniforme para la asignación de los cumpleaños. Esto se puede realizar de manera sencilla usando la función `runif` pasando los parametros correspondientes.

```{R}
# Pasamos como parametros el tamaño de la muestra, y como
# máximo y mínimo 1 y 365 que representarían los días del año
diasJugadores <- runif(sampleSize, min = 1, max = 365)
# Con el fin de sólo tomar la parte entera, usamos la función as.integer()
diasJugadores <- as.integer(diasJugadores)
# Mostramos los días generados
sort(diasJugadores)
```

Ya teniendo los valores respectivos, es sólo cuestión de mirar nuestro vector generado contiende números repetidos, que en este caso representaría jugadores con un mismo cumpleaños.

```{R}
if (sampleSize != length(unique(diasJugadores))) {
    print("Existen al menos 2 jugadores con cumpleaños iguales")
} else {
    print("No hay jugadores con cumpleaños iguales")
}
```

Teniendo esto, ahora sólo es cuestión de realizar el mismo ensayo una `n` cantidad de partidos y tomar la cantidad de veces en las que 2 jugadores compartían el mismo cumpleaños. Para seguir con la propuesta del ejercicio, se realizará 31 veces este proceso.

```{R}
n <- 31
partidosCumple <- 0

for (i in 1:n) {
    diasJugadores <- runif(sampleSize, min = 1, max = 365)
    diasJugadores <- as.integer(diasJugadores)

    if (sampleSize != length(unique(diasJugadores))) {
        partidosCumple <- partidosCumple + 1
    }
}
```
```{R, echo = FALSE}

sprintf("Partidos donde hay que repartir medallas: %s", partidosCumple)
sprintf("Total medallas: %s", (partidosCumple * 2))
```

Finalmente, nos queda repetir este experimento con el fin de determinar el porcentaje de eurocopas en las cuales las medallas fueron y no fueron suficientes.

```{R}
k <- 1000
n <- 31
medallasCompradas <- 10
medallasNecesitadas <- c()
eurocopasFail <- 0
for (j in i:k) {
    partidosCumple <- 0
    for (i in 1:n) {
        diasJugadores <- runif(sampleSize, min = 1, max = 365)
        diasJugadores <- as.integer(diasJugadores)

        if (sampleSize != length(unique(diasJugadores))) {
            partidosCumple <- partidosCumple + 1
        }
        medallasNecesitadas <- c(medallasNecesitadas, partidosCumple * 2)
    }

    if ((partidosCumple * 2) >= medallasCompradas) {
        eurocopasFail <- eurocopasFail + 1
    }
}

decimalFallas <- eurocopasFail / k
```

```{R, echo=FALSE}
cat(sprintf("De %s ensayos realizados, el %s porciento de eurocopas\nno tuvieron medallas suficientes para los jugadores", k, decimalFallas * 100))
cat(sprintf("En promedio, para cada eurocopa se necesitaban %s medallas", round(mean(medallasNecesitadas), 2)))
```